version: '3.9'

services:
  web:
    build: .
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin@123
      - DJANGO_SUPERUSER_EMAIL=subin.bajra@gmail.com
      - POSTGRES_DB=sso_server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=subin@29935
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_DB=sso_server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=subin@29935
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
